safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_width: 792
default_lang: en
default_body_class: list

author:
    name: Peter Ljunglöf
    url:  http://www.cse.chalmers.se/~peb
    company:
        name: University of Gothenburg & Chalmers University of Technology
        # url:  http://example.com/

progress: true
line_numbers: false

